- 👋 Hi, I’m @MUSAH IDRIS
- 👀 I’m interested in Food security 9
- 🌱 I’m currently learning Agronomy 
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
MUSAHIDRI9295/MUSAHIDRI9295 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
